language: generic
sudo: required
servives:
  - docker

before install:
  - docker build -t sathishsatzy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sathishsatzy/react-test npm test

after_success:
  - docker build -t sathishsatzy/multi-client ./client
  - docker build -t sathishsatzy/multi-nginx ./nginx
  - docker build -t sathishsatzy/multi-server ./server
  - docker build -t sathishsatzy/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sathishsatzy/multi-client 
  - docker push sathishsatzy/multi-nginx   
  - docker push sathishsatzy/multi-server
  - docker push sathishsatzy/multi-worker